<a href="https://colab.research.google.com/github/lucaasnathan/AprendizadoMaquinaSupervisionado/blob/main/AprendizadoMaquinaSupervisionado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nome dos integrantes: Lucas Nathan de Oliveira e Mateus dos anjos

Turma (BSI - Quarta)

Especificações técnicas para o trabalho de Aprendizado Supervisionado do 2º bimestre:

O dataset a ser treinado precisa possuir a coluna alvo para classificação. Para este trabalho os datasets do Kaggle podem ser utilizados, lembrando que espera-se os comentários sobre os resultados e a descrição das colunas (dicionário de dados se existir) para entender o problema. O dataset precisa estar limpo, sem campos nulos, e com os tipos devidamente formatados. Dados categóricos e numéricos para treinamento são necessários.

Critérios de avaliação:

1.5 sendo 0.5 para cada algoritmo implementado corretamente (Árvore de decisão, Random Forests e Regressão Logística) com comentários e código e a respectivas comparação final entre os mesmos. 0.5 para a organização do arquivo e contribuição (caso seja dupla). 1.0 para apresentação do trabalho a ser avaliado de forma individual como defesa de código.

Importando Pandas e bibliotecas:



In [10]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

sns.set()

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
%matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/ciencia_de_dados/Trabalho 3.0/exams.csv', 
                 sep=',', encoding='iso-8859-1')

In [12]:
df.head(15)


gender race/ethnicity parental level of education         lunch  \
0     male        group A                 high school      standard   
1   female        group D            some high school  free/reduced   
2     male        group E                some college  free/reduced   
3     male        group B                 high school      standard   
4     male        group E          associate's degree      standard   
5   female        group D                 high school      standard   
6   female        group A           bachelor's degree      standard   
7     male        group E                some college      standard   
8     male        group D                 high school      standard   
9     male        group C                some college  free/reduced   
10    male        group E                some college      standard   
11  female        group D                 high school      standard   
12    male        group D          associate's degree      standard   
13    male        group C                 high school      standard   
14    male        group E            some high school      standard   

   test preparation course  math score  reading score  writing score  
0                completed          67             67             63  
1                     none          40             59             55  
2                     none          59             60             50  
3                     none          77             78             68  
4                completed          78             73             68  
5                     none          63             77             76  
6                     none          62             59             63  
7                completed          93             88             84  
8                     none          63             56             65  
9                     none          47             42             45  
10               completed          99             83             85  
11               completed          80             87             90  
12               completed          77             87             85  
13               completed          74             74             73  
14               completed          81             87             85

In [13]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


Buscando valores que possuem em cada coluna:

In [14]:
df['parental level of education'].unique()

array(['high school', 'some high school', 'some college',
       "associate's degree", "bachelor's degree", "master's degree"],
      dtype=object)

In [15]:
df['gender'].unique()

array(['male', 'female'], dtype=object)

In [16]:
df['race/ethnicity'].unique()

array(['group A', 'group D', 'group E', 'group B', 'group C'],
      dtype=object)

In [17]:
df['parental level of education'].unique()

array(['high school', 'some high school', 'some college',
       "associate's degree", "bachelor's degree", "master's degree"],
      dtype=object)

In [18]:
df['test preparation course'].unique()

array(['completed', 'none'], dtype=object)

In [19]:
df['math score'].unique()

array([ 67,  40,  59,  77,  78,  63,  62,  93,  47,  99,  80,  74,  81,
        69,  58,  54,  23,  39,  83,  71,  44,  46,  51,  53,  33,  87,
        65,  79,  68,  57,  98, 100,  60,  64,  52,  36,  56,  88,  42,
        76,  49,  72,  31,  32,  97,  94,  95,  45,  75,  66,  70,  82,
        92,  30,  41,  43,  55,  73,  48,  86,  84,  50,  89,  91,  85,
        61,  35,  90,  96,  13,  38,  28,  26,  37,  29,  34,  25])

In [20]:
df['reading score'].unique()

array([ 67,  59,  60,  78,  73,  77,  88,  56,  42,  83,  87,  74,  61,
        47,  62,  44,  32,  76,  52,  69,  55,  38,  45,  68,  89,  54,
        79,  41,  65,  81,  75,  70,  46,  63,  72,  58,  53,  57,  80,
        51,  66,  82,  93,  64,  91,  43,  71, 100,  50,  33,  34,  90,
        84,  95,  98,  92,  85,  49,  86,  48,  94,  36,  28,  39,  29,
        96,  97,  40,  27,  37,  99,  31,  35])

In [21]:
df['writing score'].unique()

array([ 63,  55,  50,  68,  76,  84,  65,  45,  85,  90,  73,  57,  42,
        44,  31,  88,  54,  32,  56,  60,  89,  51,  77,  39,  71,  74,
        75,  72,  64,  82,  70,  87,  78,  49,  47,  62,  83,  48,  59,
        97,  81,  67,  69,  61,  93, 100,  53,  79,  58,  33,  86,  66,
        46,  80,  91,  92,  95,  99,  96,  28,  52,  24,  40,  43,  94,
        23,  38,  30,  35,  41,  98,  36,  27,  26,  34,  37])

In [22]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

Alterando o nome das colunas para português e excluindo coluna 'LUNCH' que não vai ser utilizada no momento

In [23]:
df.rename(columns={'gender': 'genero'}, inplace=True)
df.rename(columns={'race/ethnicity': 'raca'}, inplace=True)
df.rename(columns={'parental level of education': 'escolaridade_dos_pais'}, inplace=True)
df.rename(columns={'test preparation course': 'preparacao_para_teste'}, inplace=True)
df.rename(columns={'math score': 'pontuacao_matematica'}, inplace=True)
df.rename(columns={'reading score': 'pontuacao_leitura'}, inplace=True)
df.rename(columns={'writing score': 'pontuacao_escrita'}, inplace=True)
df.drop(columns={'lunch'}, inplace=True)

In [24]:
df.head()

genero     raca escolaridade_dos_pais preparacao_para_teste  \
0    male  group A           high school             completed   
1  female  group D      some high school                  none   
2    male  group E          some college                  none   
3    male  group B           high school                  none   
4    male  group E    associate's degree             completed   

   pontuacao_matematica  pontuacao_leitura  pontuacao_escrita  
0                    67                 67                 63  
1                    40                 59                 55  
2                    59                 60                 50  
3                    77                 78                 68  
4                    78                 73                 68

In [25]:
df.isnull().sum()


genero                   0
raca                     0
escolaridade_dos_pais    0
preparacao_para_teste    0
pontuacao_matematica     0
pontuacao_leitura        0
pontuacao_escrita        0
dtype: int64

In [26]:
df.dtypes


genero                   object
raca                     object
escolaridade_dos_pais    object
preparacao_para_teste    object
pontuacao_matematica      int64
pontuacao_leitura         int64
pontuacao_escrita         int64
dtype: object

In [27]:
df.shape


(1000, 7)